### ISSUE TITLE
[Bug] Categories - Only retaining one selected category

### ISSUE THREAD

**Issue by OoIceDeepoO** [Fledge68/WiiFlow_Lite#123]
When checking multiple categories on a game. Only one is retained, when going out of categories. I thought this might be how the program worked, but reading the wiiflow wiki there would be no purpose for the required setting if a game could not have more than one category selected.

**Comment by Fledge68** [comment]
what version are you using? I just tried selecting a game and settings 2 or more categories. leave it and come back and those categories were all still set. i even exited wiiflow and rebooted and those categories were still set.

**Comment by OoIceDeepoO** [comment]
I just started this a couple of months ago and have been using everything as fresh as possible, so 5.2.0 Wiiflow Lite.

It's interesting that you can't reproduce. 

To go from here we can:
1) I can make a video and give you my categories_lite.ini
2) I can try to work out why it works for you

Let me know your thoughts,

Wayne

-----Original Message-----

**Comment by OoIceDeepoO** [comment]
Hi Fledge68,

So, I tried this one with a clean brand new install. The only thing I added is retroarch and some neo geo games I have been playing with on the sd card. I also have some wii and a gamecube game on the harddrive.

When I tried this on one of the Neo Geo games, with a fresh install and selecting category1 and category 2, then click back. Then going back into categories only category 2 was still checked. category 1 was no longer checked. Thinking maybe the problem was isolated to the Neo Geo or plug in games. I tried it with the wii and gamecube games, but got the same result.

I am stumped on why it is consistent with me and not with you. I even tried it on our second Wii. Same result.

If you can think of any other troubleshooting steps, including:
1) Me videoing
2) Me zipping anything that you want to see and uploading it somewhere you can download it
3) Or trying anything else

Let me know and I am happy to. 

Just as a side note, I want you to know that you are sooooo appreciated. I have 3 kids 8, 6, and 2 years old. The 8 year old constantly is scratching discs, so I wanted to setup a backup loader and Wii Flow looked awesome. So, far my kids love it. Beyond that my brother and I have been rediscovering old Commodore 64 and Atari 2600 games we haven't played in years as well as playing Tecmo Bowl 2020. His birthday was last week and I know that us playing retro games made him super happy (possibly because he beats me every time). : )

Wayne aka OoIceDeepoO




-----Original Message-----

**Comment by Fledge68** [comment]
sorry you have spent so much time on this. but i think we already fixed this issue and it was fixed after v5.2.0 was released.

see issue #101 

i'm using v5.30 beta 12. I know I need to fix github readme so people know where to get beta downloads or I need to put out a new release soon.

check out the OP of wiiflow lite thread on gbatemp. it provides downloads.
https://gbatemp.net/threads/wiiflow-lite.422685/

**Comment by OoIceDeepoO** [comment]
I don't mind at all. Being in a programmer, people tell me that programs do all kinds of weird things. Usually they are not descriptive enough to help me nail down what the real issue is. Again I appreciate so much all the work you do and I am at your service.

I am going to install the beta release and try both issues and see if they still happen. I will let you know.

Wayne


-----Original Message-----

**Comment by OoIceDeepoO** [comment]
Confirmed!!! This one is absolutely fixed in 5.30 beta 12. I will close the bug if I can in GitHub.

The other one with the hidden categories unfortunately still happens, but it is not a huge bug, because the chances of anyone else coming across it are pretty slim. 

-----Original Message-----
